### ISSUE TITLE
Create infrastructure for database migrations

### ISSUE THREAD

**Issue by flavius** [metinorak/devSeater#14]

**Comment by metinorak** [comment]
Hi,

I didn't use any orm library. I just wrote sql codes one by one to do actions. So I can publish database structure (.sql file) on github.

**Comment by flavius** [comment]
Yes, do that.

But you will also make modifications to the database over time. Keep track of those modifications (also as .sql scripts, which will probably contain "ALTER TABLE" statements).

So you'll need an installation procedure (automatized) which will apply these scripts one by one.

**Comment by metinorak** [comment]
I was thinking a solution about this:
There will be a manage.py which will get parameter (like `migrate`)
Then the script drop all tables in the test database, read sql script as a file and finally execute the sql codes to create last version of the schema.

What do you think about this?

**Comment by flavius** [comment]
You will have files like:
```
sql/00_initial.sql
sql/01_featureA.sql
sql/02_featureB.sql
sql/03_bugfixC.sql
sql/04_optimizationD.sql
sql/NNN_name.sql
```
The names are arbitrary and purely informational, but the numbers matter.

You will only execute the files not already executed, so you need to know the number executed "last year", and start from there. If you don't know the number, you start at 0.

**Comment by flavius** [comment]
Looking over what is out there, this library seems like a good fit for this project https://ollycope.com/software/yoyo/latest/

I know that making everything from scratch is fun, but you don't create any value in terms of "dev seating" if you do this one yourself.

**Comment by metinorak** [comment]
Yes you're absolutely right. I will look at that library and also write documents for people how to contribute to the project.
